# Generated by Django 2.0.4 on 2019-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FEAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('review', models.TextField()),
                ('predict_label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SRD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('predict_label', models.CharField(max_length=100)),
            ],
        ),
    ]
